table People
	lineageTag: 5e549d61-1dea-47ff-8de9-a34fcb09607e

	column 'Regional Manager'
		dataType: string
		lineageTag: 1f2c0e18-057a-4403-8b40-88fb86f8745a
		summarizeBy: none
		sourceColumn: 'Regional Manager'
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 6a97046a-7d04-4117-9843-94937d181285
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	partition 'People-21dac12a-511f-470d-aa4a-91fe397ec437' = m
		mode: import
		source =
				let
				    
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\Sample - Superstore.xlsx"), null, true),
				
				            _nav = _src{[Item="People",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Regional Manager", "Region"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Regional Manager", type text},
				        {"Region", type text}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 2 columns: Regional Manager, Region.

