table Calendar
	lineageTag: f1b6b69a-8528-4219-9a1a-a9f6b8b14fc1

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 9fcc1e02-81c7-42c5-9ee5-41b4dc023425
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: c773f30b-cd36-4af5-88cb-e453c78d654a
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 9db939a2-6e85-4fd6-af06-2f5472800c17
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: fb7f393a-ef09-4e07-b67e-d2edb5b22d96
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: e1c39365-f728-4fc1-b688-0e8679522e5a
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 5111f06a-03e1-4915-b884-148405284448
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 73e12852-1dfe-4ef5-866e-de4cc943a68e
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: c6d65b55-cf9a-4f57-a24f-d9e3c36e2db3
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 42c3e6bf-a1e6-4951-a05b-6a04ad16c5f2

		level Year
			ordinal: 0
			column: Year
			lineageTag: 012603df-c109-4bf5-9a0d-49f64fa6a7bf

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 77ea2ab2-7807-40a6-ba26-950390d189b0

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 33b49446-03bb-448e-8033-aa7bbbd5f470

		level Day
			ordinal: 3
			column: Day
			lineageTag: 9b97ee81-8335-42c7-bf0e-6ce32f9ab5d4


	partition 'Calendar-c9b69850-2ef4-4a16-826c-b9e08779cb2b' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

