table Clients
	lineageTag: 1cb2da21-ca6f-4389-be50-430773a99f14

	column client_id
		dataType: int64
		lineageTag: 145cd72b-6cd9-483a-8a02-419f57d55071
		summarizeBy: sum
		sourceColumn: client_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column nom_client
		dataType: string
		lineageTag: aa14289d-cccb-4093-ad98-7b18dbde1bb6
		summarizeBy: none
		sourceColumn: nom_client

		annotation SummarizationSetBy = Automatic

	column prenom_client
		dataType: string
		lineageTag: 8f733989-ac77-46f5-a019-3f2f5303d86f
		summarizeBy: none
		sourceColumn: prenom_client

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 752d43b7-3ddb-4390-a908-4afaa820fba0
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column segment
		dataType: string
		lineageTag: d3a8d940-921a-49ff-bffc-ddb22eae6a68
		summarizeBy: none
		sourceColumn: segment

		annotation SummarizationSetBy = Automatic

	column type_client
		dataType: string
		lineageTag: c02b91e7-245b-467c-87f6-45031a4e449c
		summarizeBy: none
		sourceColumn: type_client

		annotation SummarizationSetBy = Automatic

	column date_inscription
		dataType: dateTime
		formatString: General Date
		lineageTag: de94bc4e-be05-47dd-8546-475d617acd61
		summarizeBy: none
		sourceColumn: date_inscription

		annotation SummarizationSetBy = Automatic

	partition 'Clients-1c5b9ad6-8efe-4a2b-83a9-784319b25c98' = m
		mode: import
		source =
				let
				    
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("db.entreprise.fr:5432", "ventes_db"),
				
				            _nav = _src{[Schema="public", Item="Clients"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"client_id", "nom_client", "prenom_client", "email", "segment", "type_client", "date_inscription"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"client_id", "ID Client"}, {"nom_client", "Nom du Client"}, {"prenom_client", "Prénom du Client"}, {"email", "Email"}, {"segment", "Segment"}, {"type_client", "Type de Client"}, {"date_inscription", "Date d'Inscription"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 7 columns: client_id, nom_client, prenom_client, email, segment, type_client, date_inscription.

