# ══════════════════════════════════════════════════════════════
# RLS Role Assignment Script — Ventes_France
# Generated by Tableau-to-Power-BI Migration Tool
# ══════════════════════════════════════════════════════════════
#
# Prerequisites:
#   Install-Module -Name MicrosoftPowerBIMgmt -Scope CurrentUser
#   Connect-PowerBIServiceAccount
#
# Usage:
#   1. Update $WorkspaceId and $DatasetId below
#   2. Update the email addresses for each role
#   3. Run: .\assign_rls_roles.ps1
# ══════════════════════════════════════════════════════════════

# --- Configuration ---
$WorkspaceId = "YOUR_WORKSPACE_ID"   # Replace with your workspace GUID
$DatasetId   = "YOUR_DATASET_ID"     # Replace with your dataset GUID

# Connect to Power BI Service (interactive login)
Connect-PowerBIServiceAccount

# ── Role: Accès Commercial ──
$Role_Acc_s_Commercial_Members = @(
    "user@yourdomain.com"     # TODO: Add Azure AD members
)

foreach ($member in $Role_Acc_s_Commercial_Members) {
    try {
        $body = @{ emailAddress = $member } | ConvertTo-Json
        $url = "groups/$WorkspaceId/datasets/$DatasetId/users"
        Invoke-PowerBIRestMethod -Url $url -Method Post -Body $body
        Write-Host "  Added $member to role Accès Commercial" -ForegroundColor Green
    } catch {
        Write-Host "  Failed to add $member to role Accès Commercial: $_" -ForegroundColor Red
    }
}

Write-Host ""
Write-Host "RLS role assignment complete." -ForegroundColor Cyan
