"""Compare current performance baselines against a previous CI baseline set.

This script reads one or more JSON baseline files generated by
scripts/run_perf_baseline.py and produces:
  1) a machine-readable trend diff JSON
  2) a human-readable Markdown summary

It is intentionally best-effort: missing previous data does not fail the run.
"""

import argparse
import json
import os
from datetime import datetime, timezone

LOWER_IS_BETTER_METRICS = (
    ('total_seconds', 'median'),
    ('total_seconds', 'p95'),
    ('generation_seconds', 'median'),
    ('extraction_seconds', 'median'),
    ('peak_mb', 'max'),
)


def _read_json(path):
    with open(path, encoding='utf-8') as handle:
        return json.load(handle)


def _safe_get(data, *keys):
    current = data
    for key in keys:
        if not isinstance(current, dict) or key not in current:
            return None
        current = current[key]
    return current


def _percent_delta(previous_value, current_value):
    if previous_value in (None, 0) or current_value is None:
        return None
    return ((current_value - previous_value) / previous_value) * 100.0


def _baseline_key(path, baseline):
    workbook = baseline.get('workbook')
    workbook_name = os.path.basename(workbook) if workbook else os.path.basename(path)
    output_format = baseline.get('output_format', 'unknown')
    return f'{workbook_name}:{output_format}'


def _load_baselines(folder):
    baselines = {}
    if not folder or not os.path.isdir(folder):
        return baselines

    for name in sorted(os.listdir(folder)):
        if not name.endswith('.json'):
            continue
        path = os.path.join(folder, name)
        try:
            baseline = _read_json(path)
        except (OSError, json.JSONDecodeError):
            continue
        if not isinstance(baseline, dict) or 'summary' not in baseline:
            continue
        baselines[_baseline_key(path, baseline)] = {
            'path': path,
            'data': baseline,
        }
    return baselines


def _compare_fixture(current, previous, threshold_percent):
    current_data = current['data']
    previous_data = previous['data'] if previous else None

    compared_metrics = {}
    regressions = []

    for metric_name, stat_name in LOWER_IS_BETTER_METRICS:
        current_value = _safe_get(current_data, 'summary', metric_name, stat_name)
        previous_value = _safe_get(previous_data, 'summary', metric_name, stat_name)
        delta_percent = _percent_delta(previous_value, current_value)
        compared_metrics[f'{metric_name}.{stat_name}'] = {
            'current': current_value,
            'previous': previous_value,
            'delta_percent': delta_percent,
        }
        if delta_percent is not None and delta_percent > threshold_percent:
            regressions.append({
                'metric': f'{metric_name}.{stat_name}',
                'delta_percent': delta_percent,
            })

    current_stable = current_data.get('stable')
    previous_stable = previous_data.get('stable') if previous_data else None

    return {
        'current': {
            'path': current['path'],
            'stable': current_stable,
            'schema_version': current_data.get('schema_version'),
        },
        'previous': None if not previous else {
            'path': previous['path'],
            'stable': previous_stable,
            'schema_version': previous_data.get('schema_version'),
        },
        'metrics': compared_metrics,
        'regressions': regressions,
    }


def compare_baselines(current_dir, previous_dir=None, threshold_percent=10.0):
    current_baselines = _load_baselines(current_dir)
    if not current_baselines:
        raise ValueError(f'No valid baseline JSON files found in: {current_dir}')

    previous_baselines = _load_baselines(previous_dir)

    fixtures = {}
    regression_count = 0

    for key, current in sorted(current_baselines.items()):
        previous = previous_baselines.get(key)
        fixture_result = _compare_fixture(
            current=current,
            previous=previous,
            threshold_percent=threshold_percent,
        )
        fixtures[key] = fixture_result
        regression_count += len(fixture_result['regressions'])

    return {
        'generated_at': datetime.now(timezone.utc).isoformat(),
        'threshold_percent': threshold_percent,
        'current_dir': os.path.abspath(current_dir),
        'previous_dir': None if not previous_dir else os.path.abspath(previous_dir),
        'fixtures': fixtures,
        'summary': {
            'fixtures_compared': len(fixtures),
            'fixtures_with_previous': sum(
                1 for result in fixtures.values() if result['previous'] is not None
            ),
            'regressions': regression_count,
            'status': 'regression' if regression_count > 0 else 'ok',
        },
    }


def _render_markdown(report):
    lines = []
    lines.append('# Performance Trend Diff')
    lines.append('')
    lines.append(f"- Generated: {report['generated_at']}")
    lines.append(f"- Threshold: {report['threshold_percent']:.1f}%")
    lines.append(f"- Current baselines: {report['current_dir']}")
    if report.get('previous_dir'):
        lines.append(f"- Previous baselines: {report['previous_dir']}")
    lines.append('')

    summary = report['summary']
    lines.append(
        f"Status: **{summary['status'].upper()}** "
        f"({summary['regressions']} regression(s) across {summary['fixtures_compared']} fixture(s))"
    )
    lines.append('')

    for fixture, result in sorted(report['fixtures'].items()):
        lines.append(f'## {fixture}')
        lines.append('')
        lines.append('| Metric | Previous | Current | Delta |')
        lines.append('|---|---:|---:|---:|')
        for metric_name, values in sorted(result['metrics'].items()):
            previous_value = values['previous']
            current_value = values['current']
            delta = values['delta_percent']
            previous_text = '-' if previous_value is None else f'{previous_value:.4f}'
            current_text = '-' if current_value is None else f'{current_value:.4f}'
            delta_text = '-' if delta is None else f'{delta:+.2f}%'
            lines.append(
                f'| {metric_name} | {previous_text} | {current_text} | {delta_text} |'
            )
        lines.append('')

        if result['regressions']:
            lines.append('Regressions:')
            for entry in result['regressions']:
                lines.append(
                    f"- {entry['metric']}: +{entry['delta_percent']:.2f}%"
                )
            lines.append('')

    return '\n'.join(lines).rstrip() + '\n'


def _build_parser():
    parser = argparse.ArgumentParser(
        description='Compare current performance baselines with a previous set.',
    )
    parser.add_argument(
        '--current-dir', required=True,
        help='Directory containing current baseline JSON files.',
    )
    parser.add_argument(
        '--previous-dir', default=None,
        help='Directory containing previous baseline JSON files (optional).',
    )
    parser.add_argument(
        '--threshold-percent', type=float, default=10.0,
        help='Regression threshold percentage for lower-is-better metrics.',
    )
    parser.add_argument(
        '--output-json', required=True,
        help='Path to write the trend diff JSON report.',
    )
    parser.add_argument(
        '--output-md', required=True,
        help='Path to write the Markdown summary report.',
    )
    return parser


def main(argv=None):
    args = _build_parser().parse_args(argv)
    report = compare_baselines(
        current_dir=args.current_dir,
        previous_dir=args.previous_dir,
        threshold_percent=args.threshold_percent,
    )

    output_json = os.path.abspath(args.output_json)
    output_md = os.path.abspath(args.output_md)
    os.makedirs(os.path.dirname(output_json), exist_ok=True)
    os.makedirs(os.path.dirname(output_md), exist_ok=True)

    with open(output_json, 'w', encoding='utf-8') as handle:
        json.dump(report, handle, indent=2)
        handle.write('\n')

    markdown = _render_markdown(report)
    with open(output_md, 'w', encoding='utf-8') as handle:
        handle.write(markdown)

    print(
        f"Trend diff: {report['summary']['status']} "
        f"({report['summary']['regressions']} regression(s))"
    )
    print(f'JSON report written to: {output_json}')
    print(f'Markdown report written to: {output_md}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
