table Calendar
	lineageTag: 50492395-cdc5-405e-9d61-8167c084dad6

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: bdef0fde-728b-43d2-8e5d-b98ee3f4a78f
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 0c5a883f-b14a-4824-ae40-3933481035f8
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: beebda59-c1a2-4ff9-954f-fb120f9c068d
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: c6a1bfbc-734a-40a5-9f71-517832fa672c
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: bb9ef037-58fc-46b7-96dc-36ef68bc2014
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: c5aedf62-3d6e-401a-bf52-522a9b240c3d
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: cc0228c5-4612-484a-ae8e-191e2d761a79
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: cfeaac03-4e7a-416a-b6c0-4d0f21cda193
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: bd81555a-a442-407f-8041-d09b4909b64f

		level Year
			ordinal: 0
			column: Year
			lineageTag: 3702042b-9493-4d28-8ec3-88c67401b0e6

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 18aa827a-1263-4a2d-94ab-95ccec67adb8

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: a681512a-313e-4f98-ae67-51159d829f2c

		level Day
			ordinal: 3
			column: Day
			lineageTag: d0660570-e288-4cb0-abd2-6952f517d51b


	partition 'Calendar-f65d2ee3-b2cc-44da-987e-5c774aa7c4ad' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

