table Maintenance
	lineageTag: 0d4e5f86-240f-46dc-a8a6-ca212dde07e6

	column maint_id
		dataType: int64
		lineageTag: 76629403-cc74-4412-9b8d-c7ac4d284820
		summarizeBy: sum
		sourceColumn: maint_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column machine_id
		dataType: int64
		lineageTag: 62e9c27a-5b1c-4242-9627-9b9bb64ba9d4
		summarizeBy: sum
		sourceColumn: machine_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column maint_date
		dataType: dateTime
		formatString: General Date
		lineageTag: eb655d31-2784-4359-8017-a343ed69397f
		summarizeBy: none
		sourceColumn: maint_date

		annotation SummarizationSetBy = Automatic

	column maint_type
		dataType: string
		lineageTag: 8461018f-a30d-4701-b2a1-1da7aa2293b4
		summarizeBy: none
		sourceColumn: maint_type

		annotation SummarizationSetBy = Automatic

	column maint_cost
		dataType: double
		formatString: #,0.00
		lineageTag: f112a92b-2aaf-4a52-a48d-b2e0a526637b
		summarizeBy: sum
		sourceColumn: maint_cost

		annotation SummarizationSetBy = Automatic

	column downtime_hours
		dataType: double
		formatString: #,0.00
		lineageTag: 0536ea72-b5a8-4909-9b74-9c85f64e48b4
		summarizeBy: sum
		sourceColumn: downtime_hours

		annotation SummarizationSetBy = Automatic

	column technician
		dataType: string
		lineageTag: ed13f944-1310-40aa-bb4b-5b22b143e5be
		summarizeBy: none
		sourceColumn: technician

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: b0bae569-336e-433e-ad9d-3978abc5b95c
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	partition 'Maintenance-90ac7f91-ed12-4dd4-8f0c-e70e60b470b5' = m
		mode: import
		source =
				let
				    
				    Source = try
				
				        let
				
				            _src = Oracle.Database("oracle.example.com:1521/MFGDB"),
				
				            _nav = _src{[Schema="DBO", Item="Maintenance"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"maint_id", "machine_id", "maint_date", "maint_type", "maint_cost", "downtime_hours", "technician", "description"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"maint_id", "Maint ID"}, {"machine_id", "Machine ID"}, {"maint_date", "Maint Date"}, {"maint_type", "Maint Type"}, {"maint_cost", "Maint Cost"}, {"downtime_hours", "Downtime Hours"}, {"technician", "Technician"}, {"description", "Description"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 8 columns: maint_id, machine_id, maint_date, maint_type, maint_cost, downtime_hours, technician, description.

